In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
a = pd.read_csv("/content/edu.csv")

# ***DATA INSPECTION***

In [ ]:
a

,country,date,GNP,Population,Edu_prime,Edu_second,Edu_post_second,Edu_lower_second,Unemp,c_codes
0,ARAB WORLD,2017,16997.503539,414491886.0,NaN,NaN,NaN,NaN,NaN,NaN
1,ARAB WORLD,2016,16794.064949,406452690.0,83.911949,NaN,NaN,NaN,NaN,NaN
2,ARAB WORLD,2015,16366.596405,398304960.0,84.720306,NaN,NaN,NaN,NaN,NaN
3,ARAB WORLD,2014,15895.251480,390043028.0,85.314812,NaN,NaN,NaN,NaN,NaN
4,ARAB WORLD,2013,15453.220686,381702086.0,84.703484,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
15307,ZIMBABWE,1964,NaN,4269863.0,NaN,NaN,NaN,NaN,NaN,ZWE
15308,ZIMBABWE,1963,NaN,4132756.0,NaN,NaN,NaN,NaN,NaN,ZWE
15309,ZIMBABWE,1962,NaN,3999419.0,NaN,NaN,NaN,NaN,NaN,ZWE
15310,ZIMBABWE,1961,NaN,3870756.0,NaN,NaN,NaN,NaN,NaN,ZWE
15311,ZIMBABWE,1960,NaN,3747369.0,NaN,NaN,NaN,NaN,NaN,ZWE

In [ ]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15312 entries, 0 to 15311
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   country           15312 non-null  object
 1   date              15312 non-null  int64
 2   GNP               6277 non-null   float64
 3   Population        15147 non-null  float64
 4   Edu_prime         6441 non-null   float64
 5   Edu_second        870 non-null    float64
 6   Edu_post_second   790 non-null    float64
 7   Edu_lower_second  976 non-null    float64
 8   Unemp             1692 non-null   float64
 9   c_codes           10556 non-null  object
dtypes: float64(7), int64(1), object(2)
memory usage: 1.2+ MB

In [ ]:
a.head()

,country,date,GNP,Population,Edu_prime,Edu_second,Edu_post_second,Edu_lower_second,Unemp,c_codes
0,ARAB WORLD,2017,16997.503539,414491886.0,NaN,NaN,NaN,NaN,NaN,NaN
1,ARAB WORLD,2016,16794.064949,406452690.0,83.911949,NaN,NaN,NaN,NaN,NaN
2,ARAB WORLD,2015,16366.596405,398304960.0,84.720306,NaN,NaN,NaN,NaN,NaN
3,ARAB WORLD,2014,15895.251480,390043028.0,85.314812,NaN,NaN,NaN,NaN,NaN
4,ARAB WORLD,2013,15453.220686,381702086.0,84.703484,NaN,NaN,NaN,NaN,NaN

In [ ]:
a.dtypes

country              object
date                  int64
GNP                 float64
Population          float64
Edu_prime           float64
Edu_second          float64
Edu_post_second     float64
Edu_lower_second    float64
Unemp               float64
c_codes              object
dtype: object

In [ ]:
a.columns

Index(['country', 'date', 'GNP', 'Population', 'Edu_prime', 'Edu_second',
       'Edu_post_second', 'Edu_lower_second', 'Unemp', 'c_codes'],
      dtype='object')

In [ ]:
a.shape

(15312, 10)

In [ ]:
a.isnull()

,country,date,GNP,Population,Edu_prime,Edu_second,Edu_post_second,Edu_lower_second,Unemp,c_codes
0,False,False,False,False,True,True,True,True,True,True
1,False,False,False,False,False,True,True,True,True,True
2,False,False,False,False,False,True,True,True,True,True
3,False,False,False,False,False,True,True,True,True,True
4,False,False,False,False,False,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...
15307,False,False,True,False,True,True,True,True,True,False
15308,False,False,True,False,True,True,True,True,True,False
15309,False,False,True,False,True,True,True,True,True,False
15310,False,False,True,False,True,True,True,True,True,False
15311,False,False,True,False,True,True,True,True,True,False

In [ ]:
a.notnull()

,country,date,GNP,Population,Edu_prime,Edu_second,Edu_post_second,Edu_lower_second,Unemp,c_codes
0,True,True,True,True,False,False,False,False,False,False
1,True,True,True,True,True,False,False,False,False,False
2,True,True,True,True,True,False,False,False,False,False
3,True,True,True,True,True,False,False,False,False,False
4,True,True,True,True,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
15307,True,True,False,True,False,False,False,False,False,True
15308,True,True,False,True,False,False,False,False,False,True
15309,True,True,False,True,False,False,False,False,False,True
15310,True,True,False,True,False,False,False,False,False,True
15311,True,True,False,True,False,False,False,False,False,True

In [ ]:
a.memory_usage()

Index                  132
country             122496
date                122496
GNP                 122496
Population          122496
Edu_prime           122496
Edu_second          122496
Edu_post_second     122496
Edu_lower_second    122496
Unemp               122496
c_codes             122496
dtype: int64

In [ ]:
a.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
15307    False
15308    False
15309    False
15310    False
15311    False
Length: 15312, dtype: bool

In [ ]:
a.duplicated()

NameError: name 'a' is not defined

In [ ]:
a = pd.read_csv("")

NameError: name 'pd' is not defined

In [ ]:
import pandas as pd

In [ ]:
a = pd.read_csv("/content/edu.csv")

In [ ]:
display(a.std())

In [ ]:
import pandas as pd

In [ ]:
a = pd.read_csv("/content/edu.csv")

In [ ]:
display(a.std())

In [ ]:
a.tail()

,country,date,GNP,Population,Edu_prime,Edu_second,Edu_post_second,Edu_lower_second,Unemp,c_codes
15307,ZIMBABWE,1964,NaN,4269863.0,NaN,NaN,NaN,NaN,NaN,ZWE
15308,ZIMBABWE,1963,NaN,4132756.0,NaN,NaN,NaN,NaN,NaN,ZWE
15309,ZIMBABWE,1962,NaN,3999419.0,NaN,NaN,NaN,NaN,NaN,ZWE
15310,ZIMBABWE,1961,NaN,3870756.0,NaN,NaN,NaN,NaN,NaN,ZWE
15311,ZIMBABWE,1960,NaN,3747369.0,NaN,NaN,NaN,NaN,NaN,ZWE

In [ ]:
a.size

153120

In [ ]:
a.describe()

,date,GNP,Population,Edu_prime,Edu_second,Edu_post_second,Edu_lower_second,Unemp
count,15312.000000,6277.000000,1.514700e+04,6441.000000,870.000000,790.000000,976.000000,1692.000000
mean,1988.500000,12491.472098,2.060462e+08,78.546217,49.265608,18.708057,58.146177,7.285639
std,16.741216,15285.379888,6.793067e+08,24.383345,25.871478,13.793191,28.948362,7.020108
min,1960.000000,230.000000,4.279000e+03,1.521950,0.000000,0.000000,0.600000,0.440000
25%,1974.000000,2540.000000,9.250650e+05,62.029930,27.684260,7.189883,35.586444,3.481375
50%,1988.500000,6720.000000,6.344722e+06,87.888527,49.328899,15.727490,58.988699,5.179450
75%,2003.000000,16524.097296,4.219871e+07,96.935547,73.771906,29.815498,84.879721,7.766818
max,2017.000000,128060.000000,7.530360e+09,186.054626,96.308228,69.071663,100.000000,65.089996